name: map_flutter
description: A new Flutter project.
publish_to: 'none'

  #For build bundle
  #  flutter build appbundle --target-platform android-arm,android-arm64,android-x64 --dart-define GOOGLE_API_KEY=AIzaSyDOaiRTglZiVGsdvOq1hgK4wGKRhqdQRMY --dart-define YANDEX_API_KEY_PLACES=c687c609-ae0e-4b12-8d9a-aab953d8642f

  #For build apk
  #  flutter build apk --dart-define GOOGLE_API_KEY=AIzaSyDOaiRTglZiVGsdvOq1hgK4wGKRhqdQRMY --dart-define YANDEX_API_KEY_PLACES=c687c609-ae0e-4b12-8d9a-aab953d8642f

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.3
  location: ^4.4.0
  flutter_svg: ^1.1.6
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  logger: ^1.1.0
  geocoding: ^2.0.5
  yandex_mapkit: ^3.2.0
  shared_preferences: ^2.0.15
  flutter_osm_plugin: ^0.42.0
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/images/
