name: map_flutter
description: A new Flutter project.
publish_to: 'none'


version: 1.0.4+7

# For achieving access to the key of Google API you must add this
# "--dart-define GOOGLE_API_KEY=AIzaSyDOaiRTglZiVGsdvOq1hgK4wGKRhqdQRMY"
# after command "flutter run" or if you are using Android Studio,
# you can add it to the "Additional run args:" (Edit Configurations).

# flutter run --dart-define GOOGLE_API_KEY=AIzaSyDOaiRTglZiVGsdvOq1hgK4wGKRhqdQRMY

# If there are some problems in the process of run project, you need transfer to flutter version 3.3.10.

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.3
  location: ^4.4.0
  flutter_svg: ^1.1.6
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  logger: ^1.1.0
  geocoding: ^2.0.5
  yandex_mapkit: ^3.2.0
  shared_preferences: ^2.0.15
  flutter_osm_plugin: ^0.42.0
  geolocator: ^9.0.2
  rxdart: ^0.27.7
  connectivity_plus: ^3.0.2
  app_settings: ^4.2.0
  flutter_polyline_points: ^1.0.0
  navigation_with_mapbox: ^0.0.6
  http_mock_adapter: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  test_api: any
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_app.png"

flutter_intl:
  enabled: true
  main_locale: "ru_RU"
  arb-dir: lib/l10n/intl_ru_RU.arb
  template-arb-file: intl_ru_RU.arb
  output_dir: lib/l10n/generated

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/images/
