name: map_flutter
description: A new Flutter project.
publish_to: 'none'


version: 1.0.1+2

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.3
  location: ^4.4.0
  flutter_svg: ^1.1.6
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  logger: ^1.1.0
  geocoding: ^2.0.5
  yandex_mapkit: ^3.2.0
  shared_preferences: ^2.0.15
  flutter_osm_plugin: ^0.42.0
  geolocator: ^9.0.2
  rxdart: ^0.27.7
  connectivity_plus: ^3.0.2
  app_settings: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter_intl:
  enabled: true
  main_locale: "ru_RU"
  arb-dir: lib/l10n/intl_ru_RU.arb
  template-arb-file: intl_ru_RU.arb
  output_dir: lib/l10n/generated

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/images/
